# Generated by Django 6.1.1 on 2026-09-05 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('price_text', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('giver_note', models.TextField(blank=True, null=True)),
                ('reaction', models.CharField(blank=True, choices=[('liked', 'liked'), ('disliked', 'disliked')], max_length=8, null=True)),
                ('reacted_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('given_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_items', to='gifts.person')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gifts.person')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to='gifts.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('reaction__isnull', True), ('reaction__in', ['liked', 'disliked']), _connector='OR'), name='item_reaction_valid')],
            },
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_dates', to='gifts.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='importantdate_month_range'), models.CheckConstraint(condition=models.Q(('day__gte', 1), ('day__lte', 31)), name='importantdate_day_range')],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gifts.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gifts.person')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('person_a_id__lt', models.F('person_b_id'))), name='connection_person_a_lt_b'), models.UniqueConstraint(fields=('person_a', 'person_b'), name='connection_unique_pair')],
            },
        ),
    ]
