# Generated by Django 6.1.1 on 2026-10-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='claim_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
