# Generated by Django 6.1.1 on 2026-10-08 09:19

from django.db import migrations, models
from django.db.models import F


def given_items_were_received(apps, schema_editor):
    """Give is now the hand-over, so gifts already given were received then."""

    Item = apps.get_model("gifts", "Item")
    Item.objects.filter(given_at__isnull=False).update(received_at=F("given_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0002_item_claim_released_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="received_from",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(given_items_were_received, migrations.RunPython.noop),
    ]
